### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by sescher** [hggh/phantomjs-nagios#6]
The Phantomjs JSON Output Default Encoding is UTF8 - the Ruby File expects US-ACSII.
Results in an "UNKNOWN: Could not parse JSON from phantomjs" Error.

I would suggest to simply put something like
Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8

in the top of the check_http_load_time.rb

Fixed for me several Issues with non US-ASCII Chars in title Tags

**Comment by hggh** [comment]
did you tested it with the new default Encoding as described? 

if so, you can create a PR ;)

**Comment by sescher** [comment]
yip, works for me @ production level ;-) PR done

**Comment by hggh** [comment]
thank you very much merged: #7 :yum:
